[General]

Background="frieren.jpg"
ScaleImageCropped=true
ScreenWidth=1440
ScreenHeight=900

MainColor="#A77BFF"
AccentColor="#7DC4E4"
RoundCorners=16
ScreenPadding=0
Font="JetBrainsMono Nerd Font"
FontSize=

Locale=
HourFormat="HH:mm"
DateFormat="dddd, d MMMM"

ForceRightToLeft=false
ForceLastUser=true
ForcePasswordFocus=true
ForceHideCompletePassword=false
ForceHideVirtualKeyboardButton="false"

HeaderText=""
TranslateUsernamePlaceholder=""
TranslatePasswordPlaceholder=""
TranslateShowPassword=""
TranslateLogin="Sign In"
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSession=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot="Reboot"
TranslateShutdown="Shut Down"
TranslateVirtualKeyboardButton=""
